using MediQueue.Contracts.Authentication;
using DomainUser = MediQueue.Domain.Users.User;
using DomainUserRole = MediQueue.Domain.Users.UserRole;
using WireUserRole = MediQueue.Contracts.UserRole;

namespace MediQueue.Application.Mapping;

/// <summary>
/// Turns a domain user into the contract the clients receive.
/// </summary>
/// <remarks>
/// Mapping is written out by hand rather than generated by convention. These
/// types are a boundary between what the system knows and what it is willing to
/// say, and a boundary should be readable in one place rather than inferred from
/// property names matching.
/// </remarks>
public static class UserMapper
{
    /// <summary>Maps a user to its wire representation.</summary>
    /// <param name="user">The domain user.</param>
    /// <returns>The contract.</returns>
    public static UserDto ToDto(this DomainUser user)
    {
        ArgumentNullException.ThrowIfNull(user);

        return new UserDto(user.Id, user.Username, user.FullName, user.Role.ToWire(), user.SpecialtyId);
    }

    /// <summary>Maps the domain role onto the wire role.</summary>
    /// <remarks>
    /// Written as a switch rather than a cast so that adding a role to the domain
    /// is a compile error here instead of a number quietly reinterpreted as
    /// something else on the wire. A test pins the two enums to the same values.
    /// </remarks>
    /// <param name="role">The domain role.</param>
    /// <returns>The wire role.</returns>
    /// <exception cref="ArgumentOutOfRangeException">The role is not one this system knows.</exception>
    public static WireUserRole ToWire(this DomainUserRole role) => role switch
    {
        DomainUserRole.Assistant => WireUserRole.Assistant,
        DomainUserRole.Doctor => WireUserRole.Doctor,
        _ => throw new ArgumentOutOfRangeException(nameof(role), role, "Unknown user role."),
    };
}
